-- ============================================================================
-- MKH Property — 0035: construction_project_financial_records
--
-- Dedicated table for MK Connect's new "Loonars Coffee" construction pilot
-- (Construction Project Control Core). Per the owner's decision: Loonars
-- Coffee's money is part of Loonars Jogja's own books (mkh_projects.kode =
-- 'LL', "Loonars Living") — this table does NOT duplicate the property
-- master (mkh_projects) or the general ledger (jurnal); it references LL
-- via `proyek` (same soft/string-matched convention every other table here
-- uses — no FK constraints exist anywhere in this schema, per DATABASE.md)
-- and keeps Loonars Coffee's own spend distinguishable from Loonars
-- Living's villa spend within those same books via
-- `construction_project_code`.
--
-- One row = one construction cost request's full lifecycle snapshot
-- (draft/submitted/approved/rejected/transferred/paid/posted), synced from
-- MK Connect's construction_cost_requests the moment it reaches POSTED
-- (money has actually moved) — see 0036 for the inbound receiver. This is
-- the PROJECT-CONTROL record; jurnal (posted by the same receiver, same
-- transaction) is the FINANCE-LEDGER record. `jurnal_no` is the one
-- canonical link between them, so this never double-counts against the
-- general finance table (section 29 of the brief: "one source of truth for
-- actual money").
-- ============================================================================

create table public.construction_project_financial_records (
  id bigint generated by default as identity primary key,
  proyek text not null,
  construction_project_code text not null,
  mkc_cost_request_id uuid not null,
  rab_item_description text,
  cost_code text,
  transaction_type text not null check (transaction_type in ('material_purchase', 'contractor_payment', 'other_expense')),
  description text not null,
  quantity numeric(14, 2),
  unit text,
  amount numeric(16, 2) not null check (amount > 0),
  vendor_payee text,
  requester text,
  approver text,
  payment_status text not null default 'posted' check (payment_status in ('draft', 'submitted', 'approved', 'rejected', 'transferred', 'paid', 'posted')),
  transaction_date date not null default current_date,
  reference_document text,
  wa_request_id text,
  jurnal_no text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index construction_project_financial_records_proyek_idx on public.construction_project_financial_records (proyek);
create index construction_project_financial_records_project_code_idx on public.construction_project_financial_records (construction_project_code);
create unique index construction_project_financial_records_cost_request_idx on public.construction_project_financial_records (mkc_cost_request_id);

alter table public.construction_project_financial_records enable row level security;

-- Same permissive-RLS-plus-app-layer-guard pattern as every other finance
-- table here (see DATABASE.md's note on jurnal/pengajuan/aset) — the
-- frontend uses the anon key, not a user JWT, so real access control is
-- src/lib/auth.ts's role check, not RLS.
create policy construction_project_financial_records_select on public.construction_project_financial_records
  for select using (true);
create policy construction_project_financial_records_insert on public.construction_project_financial_records
  for insert with check (true);
create policy construction_project_financial_records_update on public.construction_project_financial_records
  for update using (true);

comment on table public.construction_project_financial_records is
  'Loonars Coffee (and future MK Connect construction-project pilots) financial records — one row per posted cost request, synced from MK Connect construction_cost_requests via sync_inbound''s construction_project_financial_record branch (0036). References Loonars Jogja (proyek=LL, mkh_projects.kode) rather than duplicating the property master; construction_project_code distinguishes which physical construction the spend belongs to within those same books.';
